### ISSUE TITLE
Add DynamicObstacles

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/GridWorlds.jl#33]

**Comment by RajGhugare19** [comment]
Hello @findmyway, I am Raj Ghugare(We've talked on slack) I am ready to start contributing, Can I take up this issue?
If yes, please explain in more detail about what needs to be done.

**Comment by findmyway** [comment]
Hey @RajGhugare19 ,

Glad you are interested in this issue!

You may refer to the environment shown here: https://github.com/maximecb/gym-minigrid#dynamic-obstacles-environment

Basically, the implementation is similar to the `EmptyWorldEnv` https://github.com/JuliaReinforcementLearning/GridWorlds.jl/blob/master/src/envs/empty.jl .

The difference is that:

1. We need to define a new object (maybe named `Obstacle`) in [`objects.jl`](https://github.com/JuliaReinforcementLearning/GridWorlds.jl/blob/master/src/objects.jl) file.
1. The game logic is that, if the agent hits an obstacle or goal, then the game is over otherwise, we re-generate obstacles in each step.

Let me know if anything is not clear to you. 😁

**Comment by RajGhugare19** [comment]
Yes, thanks

**Comment by RajGhugare19** [comment]
@findmyway I have some doubts
1) In the collecting gems environment, the episode doesn't end even if all the gems are connected. What is the reason behind this? 
2) After taking a step the obstacles relocate in the vicinity of their previous respective position right?. That means if the initial position of an obstacle is (x,y), after re-locating the position can only be one of [(x+-n,y+-m)], where n,m belong to {-1,0,1}.
3) Do i have to add a condition that the obstacles can't re-allocate on the agent itself, if the agent is in the vicinity of the obstacle? Or is this adversarial behaviour by obstacles is not allowed.
Tell me if my questions aren't clear, thanks you :)

**Comment by findmyway** [comment]
1. The function to determine if the game is terminated is missing. I think @Sid-Bhatia-0 is working on it?
2. It depends on you 😁 Either randomly regenarate the positions or just move them around. I guess the logic in gym-minigrid adopts the former.
3. Again, it depends on you. I think the difficulties are different. Adding that condition will make the game eaiser. You can add a configuration to have both cases impkemented.

**Comment by Sid-Bhatia-0** [comment]
>In the collecting gems environment, the episode doesn't end even if all the gems are collected. What is the reason behind this?

Yes. Thanks for pointing out. We are still in the process of adding some essential interfaces like `get_actions`, `get_state` etc... I'll add a `get_terminal` function for the environments.

>That means if the initial position of an obstacle is (x,y), after re-locating the position can only be one of [(x+-n,y+-m)], where n,m belong to {-1,0,1}.

This seems a good idea to randomly move about ostacles around their current position.

>Do i have to add a condition that the obstacles can't re-allocate on the agent itself, if the agent is in the vicinity of the obstacle? Or is this adversarial behaviour by obstacles is allowed.

Good point. I think we can have the obstacles moving around randomly without being aware of the agent's position. It is the agent's responsibility to learn to stay away from the obstacles. So if the agent takes a step, and it so happens that obstacle also lands at the new position of the agent, then it is still game over (since it is the agent's responsibility to make careful decisions and stay away from potentially hazardous locations).
